###############################################################################
# Sub Makefile
###############################################################################

PRJDIR  := $(realpath $(CURDIR))
INCDIR  := $(PRJDIR)/inc
SRCDIR  := $(PRJDIR)/src
OBJDIR  := $(PRJDIR)/obj

BINARY  = main

include ../../Makefile.incl

# End
